--session 1
START TRANSACTION;
BEGIN TRANSACTION ISOLATION LEVEL READ COMMITTED;
SELECT SUM(rating) FROM pizzeria;
SELECT SUM(rating) FROM pizzeria;
COMMIT;
SELECT SUM(rating) FROM pizzeria;

--session 2
START TRANSACTION;
BEGIN TRANSACTION ISOLATION LEVEL READ COMMITTED;
UPDATE pizzeria SET rating = 1.0 WHERE id = 1;
COMMIT;
SELECT SUM(rating) FROM pizzeria;