--session 1
START TRANSACTION;
BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ;
UPDATE pizzeria SET rating = 3.0 WHERE id = 1;
UPDATE pizzeria SET rating = 4.0 WHERE id = 2;
COMMIT;

--session 2
START TRANSACTION;
BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ;
UPDATE pizzeria SET rating = 4.0 WHERE id = 2;
UPDATE pizzeria SET rating = 3.0 WHERE id = 1;
COMMIT;